# Generated by Django 4.1.1 on 2023-11-14 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_positions', to='users.group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'позицию в чеке',
                'verbose_name_plural': 'Поизии в чеке',
            },
        ),
    ]
