# Generated by Django 4.1.1 on 2023-11-14 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantBillPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_price', models.IntegerField(verbose_name='Стоимость')),
                ('bill_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_bill_positions', to='bills.billposition', verbose_name='Позиция в чеке')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_bill_positions', to='users.participant', verbose_name='Участник')),
            ],
            options={
                'verbose_name': 'позицию участника',
                'verbose_name_plural': 'Позиции участников',
            },
        ),
        migrations.AddField(
            model_name='billposition',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='bill_positions', through='bills.ParticipantBillPosition', to='users.participant', verbose_name='Участники'),
        ),
    ]
