# Generated by Django 4.1.1 on 2023-11-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_participantbillposition_billposition_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='billposition',
            name='parts',
            field=models.IntegerField(default=1, verbose_name='Части'),
        ),
        migrations.AddField(
            model_name='participantbillposition',
            name='personal_parts',
            field=models.IntegerField(default=1, verbose_name='Частей'),
        ),
    ]
