# Generated by Django 4.1.1 on 2023-11-14 13:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('requisites', models.CharField(max_length=100, verbose_name='Реквизиты')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'участника',
                'verbose_name_plural': 'Участники',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('group_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='users.participant', verbose_name='Организатор')),
            ],
            options={
                'verbose_name': 'группу',
                'verbose_name_plural': 'Группы',
            },
        ),
    ]
