# Generated by Django 4.1.1 on 2023-11-14 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_organizer', models.BooleanField(default=False, verbose_name='Является организатором')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_groups', to='users.group', verbose_name='Группа')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_groups', to='users.participant', verbose_name='Участник')),
            ],
            options={
                'verbose_name': 'участника группы',
                'verbose_name_plural': 'Участники групп',
            },
        ),
    ]
