# Generated by Django 4.1.1 on 2023-11-14 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_participantgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='participants', through='users.ParticipantGroup', to='users.group', verbose_name='Группы'),
        ),
        migrations.AlterField(
            model_name='group',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizer_groups', to='users.participant', verbose_name='Организатор'),
        ),
    ]
