# Generated by Django 4.1.1 on 2023-11-14 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_participant_requisites_group_requisites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='phone',
        ),
    ]
