# Generated by Django 4.1.1 on 2023-11-16 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_participant_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_uuid',
            field=models.CharField(default='', max_length=4, verbose_name='Уникальный ID'),
        ),
    ]
